### ISSUE TITLE
Adding functions to get info from minecraft player inventory, the state of live, etc?

### ISSUE THREAD

**Issue by Oteo95** [brooksc/mcpipy#12]
Hi,

I've been thinking about using minecraft as an environment to develop reinforcement learning. I want to know if it's possible to get more specific information. Some examples are:

-Life status or hungry status
-Inventory components
-Exact point that the player is looking.
-Day/night ( or time of the day)
- Location of the enemies/non players/players
-event (if you click a mouse button the block is broken os not, etc)
...

I had been looking for information about how to receive these information but i couldn't found anything. It's posible to obtain these data in the same way we receive the data with getBlock?

**Comment by phillipcutter** [comment]
As far as I know, work on the Minecraft Raspberry Pi edition is pretty dead (I think the last update was from 2013).

If possible I'd suggest looking into the more modern [Minecraft Bedrock Edition Scripting API](https://www.minecraft.net/en-us/article/scripting-api-now-public-beta) or even [Minecraft Forge for Java Edition](https://mcforge.readthedocs.io/en/1.15.x/gettingstarted/) which has a lot more flexibility.

Unfortunately, I'm not familiar enough with the Raspberry Pi Minecraft APIs to answer your question but what you're trying to do should work with the Scripting API or Minecraft Forge.

**Comment by birv2** [comment]
I would echo what mrfleap said. I still use the Pi edition of Minecraft for teaching basic Python in middle school. The advantage, of course, is that you don't need a license. But no updates means that it's getting harder and harder to use, and it's so far behind other features that "modern" Minecraft has. In my classes, I've moved much of my Minecraft stuff over to Education Edition, which is Bedrock. Many of the features you want to implement would be there, but Java edition offers way more flexibility. I'm not an expert. You can do a lot with command blocks and scripting in Bedrock, but more in Java.

**Comment by phillipcutter** [comment]
Closing this issue as it seems to be resolved. If it isn't yet resolved please comment and I'll re-open the issue.
